[general]
import = ["~/.config/alacritty/themes/themes/catppuccin_latte.toml"]

[window]
decorations = "buttonless"
startup_mode = "Maximized"

[font]
size = 15
offset = { x = 0, y = 7 }
normal = { family = "Monaspace Argon", style = "Light" }
bold = { family = "Monaspace Argon", style = "Light" }
italic = { family = "Monaspace Argon", style = "Light Italic" }
bold_italic = { family = "Monaspace Argon", style = "Light Italic" }

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001bb"

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001bf"
